In [120]:
import numpy as np
import torch

from torch.utils.data import Dataset

import torch.nn.functional as F
import torch.nn as nn

import matplotlib.pyplot as plt

import myModelinTF

from torch.optim.lr_scheduler import StepLR
import pandas as pd
import tensorflow as tf
from torch.autograd import Variable 

from statistics import mean 

In [2]:
demo = np.load('dataset_train_firsts.npy', allow_pickle=True)
print("Train firsts set size: " + str(len(demo)))

Train firsts set size: 495


In [3]:
class SeriesDataset(Dataset):

    def __init__(self, file):
        self.demo = np.load(file, allow_pickle=True)

    #len(usd)
    def __len__(self):
        return len(self.demo)

    # a_list[1] --> a__list.__getitem__(1)
    def __getitem__(self, index):
        run =self.demo[index]
        states = np.array(run[0]).T
        #states_init1 = states[1,:]
        if states.size == 0:
            print('no states in submatrix')

        actions = np.array(run[1])[:, None]

        action_count = np.array([actions[0][0], len(actions)])
        #actions_counts_array_padded = np.pad(actions_counts_array, ((0,30-len(actions_counts_array)),(0,0)), 'constant').astype('int32') 
        #states_init = np.zeros((len(actions_counts_array_padded), 10)) + states_init1
        #states_init = states[0:len(actions_counts_array),:]
       
        return states, action_count.astype('int32') 

In [4]:
def permute_them(x):
  return torch.permute(x, (1, 0, 2))

In [320]:
def fill_four_with_last(arr):
    prev = np.arange(len(arr))
    prev[arr == 4] = 0
    prev = np.maximum.accumulate(prev)

    # it can be that the first element is 4, so remove those
    temp = arr[prev]
    new_deleted = np.delete(temp, np.where(temp == 4))
    count = len(temp) - len(new_deleted)
    new = np.insert(new_deleted, 0, np.repeat(new_deleted[0], count), axis=0)
    return new

In [364]:
class PG(nn.Module):
    def __init__(self, n_actions):
        super().__init__()
        self.n_actions = n_actions

        # Policy takes input initial conditions and outputs planning route, open-loop control
        self.actor_model = nn.Sequential(
            nn.LSTM(input_size = 10, hidden_size = self.n_actions, num_layers = 1, dropout = 0.1,batch_first = True),
        )

        self.logprobs = []
        self.state_values = []
        self.rewards = []

    def forward(self, states):
        logits, (h_T, c_T)  = self.actor_model(states)
        return logits[-1]
    # Run agent in environment to create sample trajectories by generator
    # The environment model is a seq2seq model
    def generate_session(self, sysmodel, init_states, traj_idx,  t_max=50):
        norm_params = pd.read_csv('D:\\units\\thesis\\thesis\\train_reward_inverse_rl_w_sys_model\\norm_params.csv', header = None).to_numpy().T

        states, actions, actions_probs_policy, rewards = [], [], [], []
        states_init_idx = init_states[traj_idx]

        states = torch.FloatTensor(states_init_idx[0].T)
        states = states.unsqueeze(0)
        actions_taken = []
        list_actions_taken = []
        actions_probs_policy_taken = []
        list_actions_filled = []
        for t in range(t_max):
            logits = policy(states) # forward pass
            logits = logits[-1]
            probs = nn.functional.softmax(logits, -1) # get estimated actions for states
            #log_probs = nn.functional.log_softmax(logits, -1)
            
            actions_probs_policy = np.squeeze(probs).clone().detach().numpy()
            actions_probs_policy_taken.append(actions_probs_policy)
            # actions = []
            # for prob in actions_probs_policy:                  
            #     actions.append(np.random.choice(5,  p = prob))
            
            action = np.random.choice(5,  p = actions_probs_policy)
            if t==0 and action == 4:
                action = 0

            list_actions_taken.append(action)
            # actions was an array of individual type of actions to take, but also 4 meaning "keep"

            a_filled = fill_four_with_last(np.array(list_actions_taken)).tolist()
            #list_actions_filled = np.append(list_actions_filled, a)
            
            # Apply dict to go from 1,2,3,4 as action to [0,2400,0] [0,2400,1000]  [2300,0,0]  [2300,0,1000] 
            my_dict = {0:[0,2400,0], 1:[0,2400,1000], 2:[2300,0,0], 3:[2300,0,1000]}
            #actions_array = np.zeros((500,3))  
            actions_array = map(my_dict.get, a_filled)
            actions_array = np.array(list(actions_array))
            actions_array_sysmodel = np.concatenate([np.arange(actions_array.shape[0])[:,None]+1+t*len(a_filled),actions_array], axis=1) 
            actions_array_sysmodel = tf.expand_dims(actions_array_sysmodel, axis = 0, name=None)
            
            states_prev = states
            states = sysmodel(actions_array_sysmodel)

            # Revert normalized values for states
            states = states*norm_params[:,0]+norm_params[:,1]
            states_new = states

            states = torch.FloatTensor(np.array(states))
            states = torch.cat((states_prev, states), 1)

            # if done:
            #     break
        
        # print(actions_taken)
        # actions_taken = np.array(actions_taken)
        # actions_taken_reshape = actions_taken.reshape(1,t_max*states.size(dim=1), 4)
        # states_all = sysmodel(actions_taken_reshape)
        # states_all = states_new*norm_params[:,0]+norm_params[:,1]
        rewards = get_rewards(states_new, np.array(list_actions_taken))
        return states_new, list_actions_taken, np.array(actions_probs_policy_taken), rewards

In [195]:
class Critic(nn.Module):
    def __init__(self):
        super().__init__()

        self.critic_model = nn.Sequential(
            # nn.Linear(10, 32),
            # nn.ReLU(inplace=False),
            # nn.Linear(32, 1)
            nn.Conv1d(in_channels=1, out_channels=8, kernel_size=5),
            nn.LSTM(input_size = 8, hidden_size = 1, num_layers = 1, dropout = 0.1,batch_first = True),
        )

    def forward(self, state):
        state = torch.FloatTensor(state)
        #state_value = self.critic_model(state)
        logits, (state_value, c_T)  = self.critic_model(state)
        return state_value

In [304]:
def get_expected_rewards(rewards,gamma=0.9):
    G = np.zeros_like(rewards, dtype=float)
    G[-1] = rewards[-1]
    
    for idx in range(-2, -len(rewards)-1, -1):
        G[idx] = rewards[idx] + gamma * G[idx+1]
    return G

def get_critic_rewards(model,states, rewards,gamma=0.9):
    G = np.zeros_like(rewards, dtype=float)
    G[-1] = rewards[-1]
    states = states.numpy()
    for idx in range(-2, -len(rewards)+1, -1):
        out1 = model(states[:,idx-1,:])
        out2 = model(states[:,idx,:])
        G[idx] = rewards[idx] + out1.detach().numpy() - out2.detach().numpy()
    return G

def get_rewards(states, actions):
    
    states = states.numpy()
    states = states.squeeze()
    rewards = np.zeros((np.shape(states)[0],1))

    actions = actions.flatten()
    print(actions)
    max_hotspot =  np.max(states)
    if max_hotspot < 300:
        rewards[-1] = 100

    if np.where( 229 >= states[:,1].all() <= 231)[0] < 405 & np.where( 229 >= states[:,1].all() <= 231)[0] > 340:
        rewards[-1] = rewards[-1] + 100

        
    for idx in range(np.shape(states)[1]):
        idx = idx -1
        temps = np.array(states[idx])
        if temps.any() > 230:
            rewards[idx] = rewards[idx] -30
        
        subset = actions[idx-20:]
        if np.sum(np.diff(subset)) == 0:
            rewards[idx] = rewards[idx] + 20

        subset = temps[idx-10:]
        if np.sum(np.diff(subset)) < 10:
            rewards[idx] = rewards[idx] + 10

        # Save power consumption
        # if actions[idx] == 1 | actions[idx] == 3:
        #     rewards[idx] = rewards[idx] -10

        # Action 4 is encouraged , has the meaning to keep the previous action
        if actions[idx] == 4:
            rewards[idx] = rewards[idx] + 10

        temps_subset = np.array([states[idx, 1], states[idx-1, 1]])
        if np.diff(temps_subset) < 0:
            rewards[idx] = rewards[idx] - 100


    return rewards

def to_one_hot(y_tensor, ndims):
    y_tensor = y_tensor.type(torch.LongTensor).view(-1, 1)
    y_one_hot = torch.zeros(
        y_tensor.size()[0], ndims).scatter_(1, y_tensor, 1)
    return y_one_hot

In [365]:
# DEVICE
DEVICE = 'cpu'

# ENV SETUP
sysmodel = myModelinTF.load_model()
n_actions = 5

# INITILIZING POLICY AND REWARD FUNCTION
policy = PG(n_actions)
policy.to(DEVICE)

critic = Critic()
critic.to(DEVICE)

norm_params = pd.read_csv('D:\\units\\thesis\\thesis\\train_reward_inverse_rl_w_sys_model\\norm_params.csv', header = None).to_numpy().T


# LOADING EXPERT/DEMO SAMPLES
DATASETNPY = "dataset_train_firsts.npy"

dataset_inits = SeriesDataset(DATASETNPY)

##### TUNE MODEL WITH REWARD LOSS

mean_rewards = []
mean_loss = []
mean_loss_rew = []
EPISODES_TO_PLAY = 2
sample_trajs = []

return_list, sum_of_loss_list = [], []

# Retrain all params
optimizer_policy = torch.optim.Adam(policy.parameters(), 1e-1, weight_decay=1e-2)
optimizer_critic = torch.optim.Adam(critic.parameters(), 1e-1, weight_decay=1e-2)

init_states = np.load(DATASETNPY, allow_pickle=True)

criterion2 = nn.MSELoss()
for i in range(1):
    trajs = [policy.generate_session(sysmodel, init_states, l) for l in range(EPISODES_TO_PLAY)]

    for traj in trajs:
        states, actions, probs, rewards = traj
        cumulative_returns_np = np.array(get_critic_rewards(critic,states,rewards, 0.7)).squeeze()
        cumulative_returns = torch.tensor(cumulative_returns_np, dtype=torch.float32)
        cumulative_returns = (cumulative_returns - torch.mean(cumulative_returns)) # torch.mean

        actions_tensor = torch.from_numpy(np.array(actions))
        probs_tensor = torch.from_numpy(np.array(probs))

        log_probs_for_actions = torch.sum(
            probs_tensor * to_one_hot(actions_tensor, 5), dim=1)
    
        loss_policy = -log_probs_for_actions*cumulative_returns_np
        # UPDATING THE POLICY NETWORK
        optimizer_policy.zero_grad()
        loss_policy.requires_grad = True
        loss_policy.sum().backward()
        torch.nn.utils.clip_grad_norm_(policy.parameters(), 0.01)
        optimizer_policy.step()

        loss_critic = criterion2(torch.from_numpy(np.array(get_critic_rewards(critic,states,rewards, 0.7).sum())).to(torch.float32), \
                                 torch.from_numpy(np.array(get_expected_rewards(rewards, 0.7).sum())).to(torch.float32))
        # UPDATING THE CRITIC NETWORK
        optimizer_critic.zero_grad()
        loss_critic.requires_grad = True
        loss_critic.backward()
        optimizer_critic.step()

        #returns = sum(rewards)
        sum_of_loss = loss_policy.sum().detach().numpy()
        print(f"\nLoss Actor: {sum_of_loss}\n")
        print(f"\nLoss Critic: {loss_critic}\n")
        #print(f"\nCumulative return: {cumulative_returns}\n")
        #return_list.append(returns)
        sum_of_loss_list.append(sum_of_loss)
        states_plot = np.squeeze(states)

    plt.subplot(2, 2, 1)
    plt.title(f"Loss per {EPISODES_TO_PLAY} episodes")
    plt.plot(sum_of_loss_list)
    plt.grid()

    plt.subplot(2, 2, 2)
    plt.title(f"Rewards")
    plt.plot(rewards)
    plt.grid()

    # plt.subplot(2, 2, 3)
    # plt.title(f"Activations")
    # plt.plot(actions[0:50])
    # plt.grid()

    plt.subplot(2, 2, 3)
    plt.title(f"Loss Critic - last")
    plt.plot(loss_critic.detach().numpy())
    plt.grid()

    plt.subplot(2, 2, 4)
    plt.title(f"Temperatures")
    plt.plot(states_plot[0:50,:])
    plt.grid()

    # plt.show()
    plt.savefig('GCL_learning_curve.png')
    plt.close()

d:\units\thesis\thesis\train_reward_inverse_rl_w_sys_model\.venv\lib\site-packages\torch\nn\modules\rnn.py:82: UserWarning: dropout option adds dropout after all but last recurrent layer, so non-zero dropout expects num_layers greater than 1, but got dropout=0.1 and num_layers=1
  warnings.warn("dropout option adds dropout after all but last "


tf.Tensor(
[[[-0.74058646 -0.68409175 -0.71720773 -0.7117114  -0.62139535
   -0.76873463 -0.5427454  -0.61774606 -0.6180178  -0.548133  ]]], shape=(1, 1, 10), dtype=float32)
tf.Tensor(
[[[ -99.3712    -65.201225  -88.57297   -95.35304   -53.22119
   -102.34895   -28.717407  -70.47131   -58.80828   -43.18119 ]]], shape=(1, 1, 10), dtype=float32)
tf.Tensor(
[[[ 0.16389315  0.24244535 -0.18937719 -0.09152506 -0.22335479
   -0.28219402 -0.15846322  0.13358916  0.15073839  0.2699528 ]
  [-0.14438875 -0.05481023 -0.16280217 -0.24390288 -0.09241834
   -0.27498114 -0.17360915 -0.17069873 -0.12718083 -0.23335338]]], shape=(1, 2, 10), dtype=float32)
tf.Tensor(
[[[176.98259  180.9035    92.55606  136.1232    92.04928   62.78266
   121.654625 167.72626  163.80014  191.69809 ]
  [ 82.79045  101.94714  101.675476  79.25023  139.83636   65.23071
   115.72793   71.25716   83.32318   47.194687]]], shape=(1, 2, 10), dtype=float32)
tf.Tensor(
[[[-1.6443174  -1.5836564  -1.5851604  -1.485081   -1.2124687


C:\Users\LENOVO\AppData\Local\Temp\ipykernel_8076\3105431629.py:31: DeprecationWarning: Calling nonzero on 0d arrays is deprecated, as it behaves surprisingly. Use `atleast_1d(cond).nonzero()` if the old behavior was intended. If the context of this warning is of the form `arr[nonzero(cond)]`, just use `arr[cond]`.
  if np.where( 229 >= states[:,1].all() <= 231)[0] < 405 & np.where( 229 >= states[:,1].all() <= 231)[0] > 340:


tf.Tensor(
[[[-1.3016086  -1.394897   -1.4337676  -1.424152   -1.1623383
   -1.4834307  -1.2288921  -1.731621   -1.7005373  -1.6070331 ]
  [-0.34802708 -0.40215334 -0.36169937 -0.57213634 -0.15210262
   -0.49135134 -0.35424688 -0.9827227  -0.93408644 -0.86174834]
  [ 0.02609668 -0.05975431  0.14253147  0.10024876  0.29690665
    0.12356518  0.10654943 -0.37500837 -0.5110625  -0.31433284]
  [-0.04347209  0.02208549  0.15919292  0.06464441  0.10785678
    0.10425431  0.13667427 -0.0806128  -0.22075523  0.08804753]
  [ 0.7353972   0.56927085  0.6702546   0.8113594   0.5888294
    0.60122025  0.6764647   0.6540688   0.44489533  0.83003956]
  [ 0.47274277  0.5292771   0.65430725  0.51329714  0.47180185
    0.49818558  0.51911724  0.6252745   0.4648201   0.71234787]
  [ 0.35013005  0.40216693  0.5324049   0.46100855  0.50700444
    0.45927724  0.47218862  0.3704191   0.28932866  0.42411065]]], shape=(1, 7, 10), dtype=float32)
tf.Tensor(
[[[-270.78534   -254.00375   -334.46588   -361.26196   

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_8076\3105431629.py:31: DeprecationWarning: Calling nonzero on 0d arrays is deprecated, as it behaves surprisingly. Use `atleast_1d(cond).nonzero()` if the old behavior was intended. If the context of this warning is of the form `arr[nonzero(cond)]`, just use `arr[cond]`.
  if np.where( 229 >= states[:,1].all() <= 231)[0] < 405 & np.where( 229 >= states[:,1].all() <= 231)[0] > 340:
